guid:
  impl: redis # snowflake || zookeeper || redis
  zookeeper:
    connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    sessionTimeOut: 3000
  snowflake:
      machineId: 1
      datacenterId: 31
      zkLeaderSelect: false
      leaderSelectorNode: _leaderSelector_
      port: ${server.port}
      zkWorkerIdEnabled: false
      workerIdNode: _workerId_
spring:
  application:
    name: guid-generator-demo
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8081
