guid:
  impl: snowflake # || zookeeper || redis
  zookeeper:
    connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    sessionTimeOut: 3000
    cleanExecutorSize: 2
    cleanUnit: 100
  snowflake:
    zookeeper-worker-id:
      enabled: true
      node: ${spring.application.name}-worker-id
spring:
  application:
    name: guid-generator-demo
  redis:
    password: redis123456
    sentinel:
      master: mymaster
      nodes: 10.191.129.56:26380
